FROM debian:jessie
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install -y nodejs
ADD . /user_code
WORKDIR /user_code
EXPOSE 8080
ENTRYPOINT ["node", "testserver.js"]
