FROM microsoft/dotnet:2.0.0-sdk-jessie AS build-env
ADD . /user_code
WORKDIR /user_code
RUN dotnet restore
RUN dotnet publish -c Release -r ubuntu.14.04-x64 -o bin/

FROM microsoft/dotnet:2.0.0-runtime-jessie
WORKDIR /user_code
COPY --from=build-env /user_code /user_code
ENV ASPNETCORE_URLS "http://0.0.0.0:8080" 
EXPOSE 8080
RUN chmod u+x bin/mainapp
ENTRYPOINT ["bin/mainapp"]
